spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3306/selfsys
    username: pi
    password: 342521
  jpa:
    hibernate:
      ddl-auto: update #注意!不能设置为create,create会删除所有表数据然后重新创建
    #show-sql: true
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3600
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
server:
  session:
    timeout: 86400
  port: 8090
security:
  oauth2:
    resource:
      filter-order: 3
